import type { Logement, PhotoLogement } from "@/types";

function photo(id: string, url: string, piece: PhotoLogement["piece"], ordre = 0): PhotoLogement {
  return { id, logement_id: "", url: "/images/accueil/" + url, ordre, piece };
}

export const logementsDemo: Logement[] = [
  {
    id: "1",
    titre: "Studio meublé proche plage",
    description:
      "Studio confortable à quelques mètres de la plage de Kribi, idéal pour un séjour au calme.",
    ville: "Kribi",
    quartier: "Mboa Manga",
    adresse: null,
    prix_mensuel: 65000,
    type: "studio",
    nombre_pieces: 1,
    surface: 30,
    latitude: 2.944,
    longitude: 9.91,
    disponible: true,
    equipements: [],
    proprietaire_id: "temp",
    created_at: new Date().toISOString(),
    video_url: "/images/accueil/videomaison1.mp4",
    whatsapp: "237600000005",
    photos: [
      photo("p1", "studio1.PNG", "salon", 0),
      photo("p2", "studio2.PNG", "salon", 1),
      photo("p3", "chambrestudio1.PNG", "chambre", 0),
      photo("p4", "toilettestudio1.PNG", "salle_de_bain", 0),
      photo("p5", "parkingstudio2.PNG", "exterieur", 0),
      photo("p6", "plagestudio2.PNG", "exterieur", 1),
      photo("p7", "espacestudio1.PNG", "general", 0),
      photo("p8", "espacestudio2.PNG", "general", 1),
    ],
  },
  {
    id: "2",
    titre: "Chambre meublée, proche université",
    description:
      "Chambre sécurisée et meublée à Logbessou, proche des transports et des commerces.",
    ville: "Douala",
    quartier: "Logbessou",
    adresse: null,
    prix_mensuel: 45000,
    type: "chambre",
    nombre_pieces: 1,
    surface: 18,
    latitude: 4.073,
    longitude: 9.736,
    disponible: true,
    equipements: [],
    proprietaire_id: "temp",
    created_at: new Date().toISOString(),
    video_url: "/images/accueil/videomaison2.mp4",
    whatsapp: "237600000003",
    photos: [
      photo("p9", "chambre1.PNG", "chambre", 0),
      photo("p10", "chambre2.PNG", "chambre", 1),
      photo("p11", "dressingchambre1.PNG", "chambre", 2),
      photo("p12", "dressingchambre2.PNG", "chambre", 3),
      photo("p13", "tablechambre1.PNG", "salon", 0),
      photo("p14", "toilettechambre1.PNG", "salle_de_bain", 0),
      photo("p15", "toilettechambre2.PNG", "salle_de_bain", 1),
      photo("p16", "conchambre2.PNG", "general", 0),
    ],
  },
  {
    id: "3",
    titre: "Appartement 2 chambres, quartier calme",
    description:
      "Bel appartement rénové à Bonapriso, cuisine équipée et terrasse privative.",
    ville: "Douala",
    quartier: "Bonapriso",
    adresse: null,
    prix_mensuel: 180000,
    type: "appartement",
    nombre_pieces: 3,
    surface: 75,
    latitude: 4.0338,
    longitude: 9.7167,
    disponible: true,
    equipements: [],
    proprietaire_id: "temp",
    created_at: new Date().toISOString(),
    video_url: "/images/accueil/videomaison1.mp4",
    whatsapp: "237600000001",
    photos: [
      photo("p17", "appartement1.PNG", "salon", 0),
      photo("p18", "appartement2.PNG", "salon", 1),
      photo("p19", "cuisine1.PNG", "cuisine", 0),
      photo("p20", "cuisine2.PNG", "cuisine", 1),
      photo("p21", "douche1.PNG", "salle_de_bain", 0),
      photo("p22", "douche2.PNG", "salle_de_bain", 1),
      photo("p23", "terasse1.PNG", "exterieur", 0),
      photo("p24", "terasse2.PNG", "exterieur", 1),
    ],
  },
  {
    id: "4",
    titre: "Villa avec piscine, vue jardin",
    description:
      "Grande maison familiale avec piscine à Edéa, parfaite pour une famille ou une colocation.",
    ville: "Edéa",
    quartier: "Ndogbiakat",
    adresse: null,
    prix_mensuel: 350000,
    type: "maison",
    nombre_pieces: 5,
    surface: 220,
    latitude: 3.7989,
    longitude: 10.133,
    disponible: true,
    equipements: [],
    proprietaire_id: "temp",
    created_at: new Date().toISOString(),
    video_url: "/images/accueil/videomaison2.mp4",
    whatsapp: "237600000006",
    photos: [
      photo("p25", "maison1.PNG", "exterieur", 0),
      photo("p26", "maison2.PNG", "exterieur", 1),
      photo("p27", "chambremaison1.PNG", "chambre", 0),
      photo("p28", "chambremaison2.PNG", "chambre", 1),
      photo("p29", "cuisinemaison1.PNG", "cuisine", 0),
      photo("p30", "cuisinemaison2.PNG", "cuisine", 1),
      photo("p31", "salledebainmaison1.PNG", "salle_de_bain", 0),
      photo("p32", "salledebainmaison2.PNG", "salle_de_bain", 1),
    ],
  },
];