import type { Logement, PhotoLogement } from "@/types";

function photo(id: string, url: string, piece: PhotoLogement["piece"], ordre = 0): PhotoLogement {
  return { id, logement_id: "", url: "/images/accueil/" + url, ordre, piece };
}

export const logementsDemo: Logement[] = [
  {
    id: "1",
    titre: "Studio meublé proche plage",
    description: "Studio confortable à quelques mètres de la plage de Kribi.",
    ville: "Kribi", quartier: "Mboa Manga", adresse: null,
    prix_mensuel: 65000, type: "studio", nombre_pieces: 1, surface: 30,
    latitude: 2.944, longitude: 9.91, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: "/images/accueil/videomaison1.mp4", whatsapp: "237600000005",
    promo: "Visite gratuite",
    argumentMarketing: "Le préféré des voyageurs à Kribi ce mois-ci — réservé 8 fois cette semaine.",
    note: 4.8, nombreAvis: 34, vedette: true,
    photos: [
      photo("p1a", "studio1.PNG", "salon", 0),
      photo("p1b", "chambrestudio1.PNG", "chambre", 0),
      photo("p1c", "toilettestudio1.PNG", "salle_de_bain", 0),
      photo("p1d", "plagestudio2.PNG", "exterieur", 0),
      photo("p1e", "espacestudio1.PNG", "general", 0),
    ],
  },
  {
    id: "2",
    titre: "Chambre meublée, proche université",
    description: "Chambre sécurisée et meublée à Logbessou.",
    ville: "Douala", quartier: "Logbessou", adresse: null,
    prix_mensuel: 45000, type: "chambre", nombre_pieces: 1, surface: 18,
    latitude: 4.073, longitude: 9.736, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: null, whatsapp: "237600000003",
    promo: "-10% le premier mois",
    argumentMarketing: null, note: 4.3, nombreAvis: 18, vedette: false,
    photos: [
      photo("p2a", "chambre1.PNG", "chambre", 0),
      photo("p2b", "dressingchambre1.PNG", "chambre", 1),
      photo("p2c", "tablechambre1.PNG", "salon", 0),
      photo("p2d", "toilettechambre1.PNG", "salle_de_bain", 0),
      photo("p2e", "conchambre2.PNG", "general", 0),
    ],
  },
  {
    id: "3",
    titre: "Appartement 2 chambres, quartier calme",
    description: "Bel appartement rénové à Bonapriso, cuisine équipée et terrasse privative.",
    ville: "Douala", quartier: "Bonapriso", adresse: null,
    prix_mensuel: 180000, type: "appartement", nombre_pieces: 3, surface: 75,
    latitude: 4.0338, longitude: 9.7167, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: null, whatsapp: "237600000001",
    promo: null,
    argumentMarketing: "Coup de cœur Open Doors — quartier sécurisé et bien desservi.",
    note: 4.9, nombreAvis: 52, vedette: true,
    photos: [
      photo("p3a", "appartement1.PNG", "salon", 0),
      photo("p3b", "cuisine1.PNG", "cuisine", 0),
      photo("p3c", "douche1.PNG", "salle_de_bain", 0),
      photo("p3d", "terasse1.PNG", "exterieur", 0),
      photo("p3e", "terasse2.PNG", "exterieur", 1),
    ],
  },
  {
    id: "4",
    titre: "Villa avec piscine, vue jardin",
    description: "Grande maison familiale avec piscine à Edéa, parfaite pour une famille ou une colocation.",
    ville: "Edéa", quartier: "Ndogbiakat", adresse: null,
    prix_mensuel: 350000, type: "maison", nombre_pieces: 5, surface: 220,
    latitude: 3.7989, longitude: 10.133, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: "/images/accueil/videomaison2.mp4", whatsapp: "237600000006",
    promo: "Visite gratuite",
    argumentMarketing: "Rare sur le marché à Edéa — piscine privée et grand jardin clôturé.",
    note: 4.7, nombreAvis: 21, vedette: true,
    photos: [
      photo("p4a", "maison1.PNG", "exterieur", 0),
      photo("p4b", "chambremaison1.PNG", "chambre", 0),
      photo("p4c", "cuisinemaison1.PNG", "cuisine", 0),
      photo("p4d", "salledebainmaison1.PNG", "salle_de_bain", 0),
      photo("p4e", "maison2.PNG", "exterieur", 1),
    ],
  },
  {
    id: "5",
    titre: "Studio cosy centre-ville",
    description: "Studio pratique proche des commerces.",
    ville: "Douala", quartier: "Akwa", adresse: null,
    prix_mensuel: 70000, type: "studio", nombre_pieces: 1, surface: 28,
    latitude: 4.0483, longitude: 9.698, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: null, whatsapp: "237600000007",
    promo: null, argumentMarketing: null, note: 4.1, nombreAvis: 9, vedette: false,
    photos: [
      photo("p5a", "studio2.PNG", "salon", 0),
      photo("p5b", "chambrestudio1.PNG", "chambre", 0),
      photo("p5c", "toilettestudio1.PNG", "salle_de_bain", 0),
      photo("p5d", "parkingstudio2.PNG", "exterieur", 0),
      photo("p5e", "espacestudio2.PNG", "general", 0),
    ],
  },
  {
    id: "6",
    titre: "Chambre meublée à Bonamoussadi",
    description: "Chambre calme et sécurisée.",
    ville: "Douala", quartier: "Bonamoussadi", adresse: null,
    prix_mensuel: 50000, type: "chambre", nombre_pieces: 1, surface: 20,
    latitude: 4.083, longitude: 9.75, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: null, whatsapp: "237600000008",
    promo: "Visite gratuite", argumentMarketing: null, note: 4.4, nombreAvis: 15, vedette: false,
    photos: [
      photo("p6a", "chambre2.PNG", "chambre", 0),
      photo("p6b", "dressingchambre2.PNG", "chambre", 1),
      photo("p6c", "toilettechambre2.PNG", "salle_de_bain", 0),
      photo("p6d", "tablechambre1.PNG", "salon", 0),
      photo("p6e", "conchambre2.PNG", "general", 0),
    ],
  },
  {
    id: "7",
    titre: "Appartement 3 pièces à Deido",
    description: "Appartement lumineux proche du pont.",
    ville: "Douala", quartier: "Deido", adresse: null,
    prix_mensuel: 150000, type: "appartement", nombre_pieces: 3, surface: 68,
    latitude: 4.062, longitude: 9.71, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: null, whatsapp: "237600000009",
    promo: null, argumentMarketing: null, note: 4.2, nombreAvis: 11, vedette: false,
    photos: [
      photo("p7a", "appartement2.PNG", "salon", 0),
      photo("p7b", "cuisine2.PNG", "cuisine", 0),
      photo("p7c", "douche2.PNG", "salle_de_bain", 0),
      photo("p7d", "terasse2.PNG", "exterieur", 0),
      photo("p7e", "terasse1.PNG", "exterieur", 1),
    ],
  },
  {
    id: "8",
    titre: "Studio face à la mer",
    description: "Vue directe sur l'océan.",
    ville: "Kribi", quartier: "Centre-ville", adresse: null,
    prix_mensuel: 90000, type: "studio", nombre_pieces: 1, surface: 34,
    latitude: 2.9375, longitude: 9.9074, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: null, whatsapp: "237600000010",
    promo: "-15% pour 3 mois", argumentMarketing: null, note: 4.6, nombreAvis: 27, vedette: false,
    photos: [
      photo("p8a", "studio1.PNG", "salon", 0),
      photo("p8b", "studio2.PNG", "salon", 1),
      photo("p8c", "plagestudio2.PNG", "exterieur", 0),
      photo("p8d", "espacestudio2.PNG", "general", 0),
      photo("p8e", "toilettestudio1.PNG", "salle_de_bain", 0),
    ],
  },
  {
    id: "9",
    titre: "Maison familiale à Kribi",
    description: "Grande maison proche de la plage.",
    ville: "Kribi", quartier: "Mboa Manga", adresse: null,
    prix_mensuel: 220000, type: "maison", nombre_pieces: 4, surface: 150,
    latitude: 2.95, longitude: 9.905, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: null, whatsapp: "237600000011",
    promo: null, argumentMarketing: null, note: 4.5, nombreAvis: 19, vedette: false,
    photos: [
      photo("p9a", "maison2.PNG", "exterieur", 0),
      photo("p9b", "chambremaison2.PNG", "chambre", 0),
      photo("p9c", "cuisinemaisson2.PNG", "cuisine", 0),
      photo("p9d", "salledebainmaison2.PNG", "salle_de_bain", 0),
      photo("p9e", "maison1.PNG", "exterieur", 1),
    ],
  },
  {
    id: "10",
    titre: "Chambre étudiante à Edéa",
    description: "Chambre simple et abordable.",
    ville: "Edéa", quartier: "Ndogbiakat", adresse: null,
    prix_mensuel: 30000, type: "chambre", nombre_pieces: 1, surface: 15,
    latitude: 3.8, longitude: 10.135, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: null, whatsapp: "237600000012",
    promo: "Visite gratuite", argumentMarketing: null, note: 4.0, nombreAvis: 7, vedette: false,
    photos: [
      photo("p10a", "chambre1.PNG", "chambre", 0),
      photo("p10b", "chambre2.PNG", "chambre", 1),
      photo("p10c", "toilettechambre1.PNG", "salle_de_bain", 0),
      photo("p10d", "dressingchambre1.PNG", "chambre", 2),
      photo("p10e", "conchambre2.PNG", "general", 0),
    ],
  },
  {
    id: "11",
    titre: "Appartement moderne à Edéa",
    description: "Appartement neuf, bien situé.",
    ville: "Edéa", quartier: "Centre-ville", adresse: null,
    prix_mensuel: 110000, type: "appartement", nombre_pieces: 2, surface: 55,
    latitude: 3.805, longitude: 10.14, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: null, whatsapp: "237600000013",
    promo: null, argumentMarketing: null, note: 4.3, nombreAvis: 13, vedette: false,
    photos: [
      photo("p11a", "appartement1.PNG", "salon", 0),
      photo("p11b", "appartement2.PNG", "salon", 1),
      photo("p11c", "douche2.PNG", "salle_de_bain", 0),
      photo("p11d", "cuisine1.PNG", "cuisine", 0),
      photo("p11e", "terasse1.PNG", "exterieur", 0),
    ],
  },
  {
    id: "12",
    titre: "Villa avec jardin à Douala",
    description: "Maison spacieuse à Bonapriso.",
    ville: "Douala", quartier: "Bonapriso", adresse: null,
    prix_mensuel: 400000, type: "maison", nombre_pieces: 6, surface: 280,
    latitude: 4.035, longitude: 9.72, disponible: true, equipements: [],
    proprietaire_id: "temp", created_at: new Date().toISOString(),
    video_url: null, whatsapp: "237600000014",
    promo: "-10% le premier mois", argumentMarketing: null, note: 4.6, nombreAvis: 24, vedette: false,
    photos: [
      photo("p12a", "maison1.PNG", "exterieur", 0),
      photo("p12b", "chambremaison1.PNG", "chambre", 0),
      photo("p12c", "chambremaison2.PNG", "chambre", 1),
      photo("p12d", "salledebainmaison1.PNG", "salle_de_bain", 0),
      photo("p12e", "maison2.PNG", "exterieur", 1),
    ],
  },
];

export const logementsVedette = () => logementsDemo.filter((l) => l.vedette);